name: GCC Toolchain for AArch64 with NewLib

on: [ push ]

env:
  BUILD_DIR: build
  TARGET: aarch64-eabi
  PREFIX: /opt/${TARGET}

jobs:
  binutils:
    name: binutils
    runs-on: ubuntu-latest

    strategy:
      matrix:
        binutils: [ 2.36.1 ]
        gcc:      [ 11.1.0 ]
        newlib:   [ 4.1.0 ]

    env:
      BINUTILS_DIR:     binutils
      BINUTILS_VERSION: ${{ matrix.binutils }}
      GCC_DIR:          gcc
      GCC_VERSION:      ${{ matrix.gcc }}
      NEWLIB_DIR:       newlib
      NEWLIB_VERSION:   ${{ matrix.newlib }}

    steps:
      - name: Download binutils ${{ env.BINUTILS_VERSION }}
        run: curl https://mirrors.syringanetworks.net/gnu/binutils/binutils-${BINUTILS_VERSION}.tar.gz --output binutils-${BINUTILS_VERSION}.tar.gz
      - name: Download GCC ${{ env.GCC_VERSION }}
        run: curl https://ftp.mpi-inf.mpg.de/mirrors/gnu/mirror/gcc.gnu.org/pub/gcc/releases/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.gz --output gcc-${GCC_VERSION}.tar.gz
      - name: Download newlib ${{ env.NEWLIB_VERSION }}
        run: curl ftp://sourceware.org/pub/newlib/newlib-${NEWLIB_VERSION}.tar.gz --output newlib-${NEWLIB_VERSION}.tar.gz

      - name: Extract files
        run: |
          tar -xzf binutils-${BINUTILS_VERSION}.tar.gz
          tar -xzf gcc-${GCC_VERSION}.tar.gz
          tar -xzf newlib-${NEWLIB_VERSION}.tar.gz

      - name: Make directory structure
        run: |
          mkdir -p ${BUILD_DIR}/${BINUTILS_DIR}
          mkdir -p ${BUILD_DIR}/${GCC_DIR}
          mkdir -p ${BUILD_DIR}/${NEWLIB_DIR}

      - name: Configure binutils ${{ env.BINUTILS_VERSION }}
        run: |
          cd ${BUILD_DIR}/${BINUTILS_DIR}
          ../binutils-${BINUTILS_VERSION}/configure --target=${TARGET} --prefix=${PREFIX}

      - name: Build binutils ${{ env.BINUTILS_VERSION }}
        run:  make all

      - name: Install binutils ${{ env.BINUTILS_VERSION }}
        run:  make install

      - name: Configure GCC ${{ env.GCC_VERSION }}
        run: |
          cd ${BUILD_DIR}/${GCC_DIR}
          ../gcc-${GCC_VERSION}/configure --target=${TARGET} --prefix=${PREFIX} --without-headers --with-newlib --with-gnu-as --with-gnu-ld

      - name: Build GCC ${{ env.GCC_VERSION }}
        run:  make all-gcc

      - name: Install GCC ${{ env.GCC_VERSION }}
        run:  make install-gcc

      - name: Configure newlib ${{ env.NEWLIB_VERSION }}
        run: |
          cd ${BUILD_DIR}/${GCC_DIR}
          ../newlib-${NEWLIB_VERSION}/configure --target=${TARGET} --prefix=${PREFIX}

      - name: Build newlib ${{ env.NEWLIB_VERSION }}
        run:  make all

      - name: Install newlib ${{ env.NEWLIB_VERSION }}
        run:  make install

      - name: Configure GCC ${{ env.GCC_VERSION }}
        run: |
          cd ${BUILD_DIR}/${GCC_DIR}
          ../gcc-${GCC_VERSION}/configure --target=$TARGET --prefix=$PREFIX --with-newlib --with-gnu-as --with-gnu-ld --disable-shared --disable-libssp

      - name: Build GCC ${{ env.GCC_VERSION }}
        run:  make all

      - name: Install GCC ${{ env.GCC_VERSION }}
        run:  make install
