name: Testing Matrix-Builds and Dependencies

on: [ push ]

jobs:
  binutils:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binutils: [ bin_1, bin_2 ]
    
    steps:
      - name: binutils ${{ matrix.binutils }}
        run: |
          mkdir -p /opt/cross/binutils
          echo "binutils ${{ matrix.binutils }}" > /opt/cross/binutils/binutils.txt
          cat /opt/cross/**/*.txt > artifact.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binutils-${{ matrix.binutils }}
          path: |
            /opt/cross
          retention-days: 1

  gcc-bootstrap:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binutils: [ bin_1, bin_2  ]
        gcc:      [ gcc_9, gcc_10 ]
    
    needs: [ binutils ]
    
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: binutils-${{ matrix.binutils }}

      - name: gcc ${{ matrix.gcc }}
        run: |
          mkdir -p /opt/cross/gcc
          echo "gcc ${{ matrix.gcc }}" > /opt/cross/gcc/gcc.txt
          cat /opt/cross/**/*.txt > artifact.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binutils-${{ matrix.binutils }}
          path: |
            /opt/cross
          retention-days: 1
          
#  newlib:
#    strategy:
#      matrix:
#        version: [ lib_20, lib_21 ]
  
#  gcc:
#    strategy:
#      matrix:
#        version: [ gcc_9, gcc_10 ]
