name: Testing Matrix-Builds and Dependencies

on: [ push ]

jobs:
  binutils:
    name:    binutils ${{ matrix.binutils }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binutils: [ 1.1, 2.1 ]
    
    steps:
      - name: binutils ${{ matrix.binutils }}
        run: |
          mkdir -p /opt/cross/binutils
          echo "binutils ${{ matrix.binutils }}" > /opt/cross/binutils/binutils.txt
          cat /opt/cross/**/*.txt > /opt/cross/artifact.txt

      - name: Testing binutils
        run: |
          cat /opt/cross/artifact.txt

      - name: Upload binutil artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binutils-${{ matrix.binutils }}
          path: /opt/cross
          retention-days: 1

  gcc-bootstrap:
    name:    binutils ${{ matrix.binutils }} => gcc ${{ matrix.gcc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binutils: [ 1.1, 2.1  ]
        gcc:      [ 9.0, 10.0 ]
    
    needs: [ binutils ]
    
    steps:
      - name: Download artifacts from 'binutils' job
        uses: actions/download-artifact@v2
        with:
          name: binutils-${{ matrix.binutils }}
          path: /opt/cross

      - name: Checking binutils
        run: |
          ls -lAh /opt
          ls -lAh /opt/cross
          cat /opt/cross/artifact.txt

      - name: gcc ${{ matrix.gcc }}
        run: |
          mkdir -p /opt/cross/gcc
          echo "gcc ${{ matrix.gcc }}" > /opt/cross/gcc/gcc.txt
          cat /opt/cross/**/*.txt > /opt/cross/artifact.txt

      - name: Testing binutils
        run: |
          cat /opt/cross/artifact.txt

      - name: Upload gcc artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binutils-${{ matrix.binutils }}-gcc-${{ matrix.gcc }}
          path: /opt/cross
          retention-days: 1

  newlib:
    name:    binutils ${{ matrix.binutils }} => gcc ${{ matrix.gcc }} with newlib ${{ matrix.newlib }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binutils: [ 1.1, 2.1  ]
        gcc:      [ 9.0, 10.0 ]
        newlib:   [ 4.0.1, 4.1.0 ]
    
    needs: [ gcc-bootstrap ]
    
    steps:
      - name: Download artifacts from 'gcc-bootstrap' job
        uses: actions/download-artifact@v2
        with:
          name: binutils-${{ matrix.binutils }}-gcc-${{ matrix.gcc }}
          path: /opt/cross

      - name: Check binutils and gcc
        run: |
          cat /opt/cross/artifact.txt

      - name: newlib ${{ matrix.newlib }}
        run: |
          mkdir -p /opt/cross/newlib
          echo "newlib ${{ matrix.newlib }}" > /opt/cross/newlib/newlib.txt
          cat /opt/cross/**/*.txt > /opt/cross/artifact.txt

      - name: Testing binutils
        run: |
          cat /opt/cross/artifact.txt

      - name: Upload gcc with newlib artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binutils-${{ matrix.binutils }}-gcc-${{ matrix.gcc }}-newlib-${{ matrix.newlib }}
          path: /opt/cross
          retention-days: 1

#  gcc:
#    strategy:
#      matrix:
#        version: [ gcc_9, gcc_10 ]
